version: '3.7'

services:

  nginx:
    image: nginx:latest
    volumes:
      - "./compose/nginx/conf.d:/etc/nginx/conf.d"
      - "./dist:/www/dist"
    ports:
      - "0.0.0.0:80:80"
    restart: always
