version: '3.7'

networks:
  train-hard:
    external: true

services:
  front:
    image: iriskin/train-hard-front:latest
    volumes:
      - ./certs:/certs
    ports:
      - "0.0.0.0:443:443"
    networks:
      - train-hard
    restart: always
