version: '3.7'

networks:
  train-hard:
    external: true

services:
  front:
    image: iriskin/train-hard-front:latest
    ports:
      - "0.0.0.0:80:80"
    networks:
      - train-hard
    restart: always
